// v5.0.901
(function(m,g,y,N,D,E,z,A,S,s,v,ea,w,B,F,O,T,fa,U,r){function V(a,b,c){if(!a)for(a in p)return p[a];var d=new ga(a);c&&d.sa();return p[b||a]=d}function W(a){for(var b in p)p[T](b)&&a(p[b])}function pa(a,b){return function(){a.call(b)}}function C(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,v):a.attachEvent(d||"on"+b,c)}function u(a,b){return function(){a(b)}}function G(a,b,c){if(!qa)if("function"==typeof a)a();else if(ra.test(a))"string"!=typeof b&&(c=b,b=0),V(a,b,c||c===r);else if(/^_/.test(a))P[a]&&
P[a](b,c),delete P[a];else{a=a[w](".");var d;1<a[F]&&(d=a.shift());a=a[0];if("get"==a)return sa(d,b);"set"==a?Q(d,b,c):"track"==a?X(Y,d,b,c):"event"==a?X(ha,d,b,c):"cancel"==a?ta(d):"noCookies"==a?Q(d,1,v):"anonymizeIP"==a?Q(d,2,s):"tag"==a?Q(d,3,b):"load"==a&&b&&b()}}function Q(a,b,c){var d=ia[(b+"")[O]()]||b;a?p[a].s(d,c):W(function(a){a.s(d,c)})}function sa(a,b){var c=ia[(b+"")[O]()]||b,d;if(a)return p[a].b(c);W(function(a){d=a.b(c)});return d}function H(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&
1)}function ja(a,b){function c(a){return"expires="+(new E(a)).toGMTString()+";"}var d="path=/;",e=a.b(6);e&&(d+="domain="+e+";");return{L:function(e,f){a.b(1,s)&&(g.cookie=e+"="+f+";"+c(+new E+(b?6E10:6E4))+d)},H:function(b){if(a.b(1,s))return(g.cookie.match("(^|;)\\s*"+b+"=(.*?)(;|$)")||[])[2]||r},X:function(a){g.cookie=a+"=;"+c(0)+d}}}function X(a,b,c,d){b?a.call(p[b],c,d):W(function(b){a.call(b,c,d)})}function ta(a){X(function(){this.C()},a)}function ga(a){var b=this;b.c=a;b.Aa=v;var c=[];b.s=
function(a,b){c[a]=b};b.b=function(a,b){return a in c?c[a]:b};var d;b.sa=function(){d=z(pa(Y,b),200)};b.C=function(){A(b.g);A(d)}}function Y(a,b){var c=this,d=ua(c,a,b),e=va(c),h=wa(c,!e.I,a!==r),f=xa(),k=ya(a),q=Z(),g=c.b(5);A(c.g);c.k=0;c.f=v;$(c);!c.b(9)&&d.ca||(d.ba||y&&"preview"==y.loadPurpose)||f.d.m&&f.d.l&&10>f.d.m&&10>f.d.l||(c.p=q.j,c.o=q.h,d={a:c.c,cs:f.V,cd:f.D,fl:f.aa,je:f.da,la:f.ea,sw:f.d.m,sh:f.d.l,dp:f.$,dm:d.Z,pa:d.ha,pt:d.ra,pr:d.ka,po:d.ma,ri:e.I,ru:e.oa,ui:h.id,re:h.qa,vi:h.va,
pv:h.na,lv:h.fa,vw:q.P,vh:q.O,dw:q.G,dh:q.F,st:q.j,sl:q.h,tv:"5.0",un:c.b(3),pp:h.ja,cp:h.W,ec:g,aip:c.b(2)?1:r},c.s(11,h.id),t&&(c.uid=h.id),a===r&&(d.id=c.id),e.K&&(d.oe=e.K.xa,d.ok=e.K.za),k&&(d.c_n=k.S,d.c_s=k.T,d.c_m=k.R,d.c_c=k.Q,d.c_t=k.U),I?(d.o_si=I,d.o_vi=aa,d.o_ci=ba):c.J=s,c.ia=0,ca("pv",d,function(a){a!==r&&(c.id=a,A(c.g),c.g=z(u(R,c),5E3))},5),c.id===r?(z(u(za,c),500),C(m,"beforeunload",u(Aa,c))):a!==r&&(c.id=r))}function ha(a,b){if("string"==typeof b||"number"==typeof b)b={caption:b};
b||(b={});b.gs_evt_name=a;R(this,"event",b)}function R(a,b,c){if(a.id!==r){if(!c){var d=Z();c={vw:d.P,vh:d.O,dw:d.G,dh:d.F,st:d.j,sl:d.h,mst:a.p,msl:a.o}}c.a=a.c;c.u=a.b(11);c.i=a.id;c.e=b;c._=D.random();c.tv="5.0";c.et=Ba(a);a.J&&I&&(a.J=v,c.o_si=I,c.o_vi=aa,c.o_ci=ba);ca("ping",c,function(){A(a.g);a.g=z(u(R,a),[7E3,12E3][a.ia++]||17500+5E3*D.random())},5)}else z(function(){R(a,b,c)},5E3)}function ka(){var a=m.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){I=a;aa=c;ba=d})}function ca(a,b,
c,d){var e=["data.gosquared.com/"],h=g[fa]("head")[0],f=g[ea]("script"),k=v,q=z(function(){f&&h.removeChild(f);f=null;da=(da+1)%e[F];b.et&&(b.et=0);--d&&ca(a,b,c,d)},1E4);b.cb=Ca(function(a){c(a);A(q)});var l=a+"?"+function(a){var b=[],c;for(c in a)a[T](c)&&a[c]!==r&&b.push(S(c)+"="+S(a[c]));return b.join("&")}(b);f.src=("https:"==J().B?"https:":"http:")+"//"+e[da]+l;f.onload=f.onreadystatechange=function(a){a=this.readyState;k||a&&"loaded"!=a&&"complete"!=a||(k=s,f&&h.removeChild(f),f=null)};h.appendChild(f)}
function Ca(a){var b="_"+Da++;P[b]=a;return b}function K(a){function b(){var a=e.name;a&&(e.name=a[w](c)[0])}var c=":_GS_:",d;if(K.M)return K.M;var e=m.top;K.M=d={Y:function(){b();e.name=(e.name||"")+c+[a,d.uid,d.r]}};try{var h=e.name||"";if(-1!=h[U](c)){var f=h[w](c)[1][w](",");f[0]==a&&(d.uid=f[1]||"",d.r=f[2]||"")}b()}catch(k){e={}}return d}function ua(a,b,c){b=J(J(b).w);return{ha:b.ua+(a.b(7,s)?b.N:"")[B](/[?&](utm_.*?|gclid)=[^&]*/g,"")[B](/^&/,"?")+(a.b(8)?b.ta:""),ra:c!==r?c:g.title,Z:b.t,
ka:b.B,ma:b.A||"-",ca:"file:"==b.B||"localhost"==b.t,ba:/fb_xd_(bust|fragment)/.test(b.w)}}function ya(a){a=J(a).N;var b,c,d,e;b=/[?&]([^=]+)=([^&]*)/g;c={};for(e=decodeURIComponent;d=b.exec(a[B](/\+/g," "));c[e(d[1])]=e(d[2]));var h;if(a&&(h=c.utm_campaign))return{S:h,T:c.utm_source,R:c.utm_medium,U:c.utm_term,Q:c.utm_content}}function xa(){var a={d:{m:0,l:0},D:"-",ea:(y.language||y.browserLanguage||"-")[O](),da:+y.javaEnabled(),V:g.characterSet||g.charSet||"-",aa:function(a,c){var d,e,h,f,k;if(y&&
(d=y.plugins)&&0<(e=d[F]))for(k=0;k<e;k++){if(-1<(f=d[k]).name[U](h=a+" "+c))return d=f.description[w](h+" "),d[1]}else if(d=m.ActiveXObject){try{if(f=(new d((h=a+c+".")+a+c)).GetVariable("$version"))return f=f[w](" ")[1][w](","),f[0]+"."+f[1]+" r"+f[2]}catch(q){}for(k=13;--k;)try{if(f=new d(h+h+k),self.ya=f&&f.wa,f)return k+".0"}catch(g){}}return"-"}("Shockwave","Flash"),$:m.devicePixelRatio||1};N&&(a.d={m:N.width,l:N.height},a.D=N.colorDepth);return a}function Z(){function a(a){return m["inner"+
a]||d&&d[e="client"+a]||c&&c[e]}function b(a){return D.max(c[e="scroll"+a],d[e],c[e="offset"+a],d[e],c[e="client"+a],d[e])}var c=g.body,d=g.documentElement,e;return{P:a("Width"),O:a("Height"),G:b("Width"),F:b("Height"),h:m.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,j:m.pageYOffset||c&&c.scrollTop||d&&d.scrollTop||0}}function $(a){A(a.ga);a.ga=z(u(la,a),15E3);a.f||(a.f=s,a.n=+new E)}function la(a){a.f&&(a.f=v,a.k=(a.k||0)+ +new E-a.n)}function Ba(a){var b=a.k,c=+new E;a.f&&(b+=c-a.n,a.n=c);a.k=
0;return b}function Ea(a){$(a);var b=Z();b.j>a.p&&(a.p=b.j);b.h>a.o&&(a.o=b.h)}function za(a){var b=u($,a);C(g,"mousemove",b);C(g,"keydown",b);C(m,"scroll",u(Ea,a));C(g,"focus",b,"focusin");C(g,"blur",u(la,a),"focusout")}function va(a){a=a.b(10,g.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=J(a).t[U](g.domain);return{I:+(0<=b&&8>=b),oa:a}}function Aa(a){if(a.id!==r){var b=ja(a);a.b(1,s)?b.L("gs_p_"+a.c,a.id):(b=K(a.c),b.r=a.id,b.Y())}}function wa(a,b,c){var d=ja(a,
1),e=K(a.c),h=d.H("gs_u_"+a.c)||e.uid,f=1,k=1,q=(h||"")[w](":"),g,l=s,n=0,m;h&&/^[0-9\:]*$/.test(h)?(h=q[0],f=((q[1]||2019)-2019)/548+ +!!b,k=((q[2]||4621)-4621)/379+1,n=(q[3]||0)/1E3):(l=v,h=0|2147483647*D.random());d.L("gs_u_"+a.c,e.uid=[h,2019+548*f,4621+379*k,+new E].join(":"));b=d.H("gs_p_"+a.c)||e.r;b!==r&&(m=b,d.X("gs_p_"+a.c));c&&(m=a.id);if((a=a.b(4))&&"object"==typeof a){g=[];for(var p in a)a[T](p)&&g.push(p+"="+("gravatar"==p?Fa(a[p][B](/^\s+|\s+$/g,"")[O]()):a[p]));g=g.join("|")}return{id:+h,
va:f,na:k,fa:~~n,qa:l,ja:m,W:g}}var L,l=m._gs||(L=s,function(){ma.push(arguments)}),ma=l.q=l.q||[];if(!l.v){var ra=/^GSN-.*-.$/,p={},t=m.GoSquared;if(t){var n,M;for(n in t)M=t[n],"acct"==n?(V(M,"default",s),l(function(){function a(a){b[a.shift()].apply(b,a)}var b=t.DefaultTracker=p["default"];if(n=t.q)for(;M=n.shift();)a(M);t.q={push:a};(n=t.load)&&n(b)})):"load"!=n&&"q"!=n&&l("set",n,M);n=ga.prototype;n.TrackView=Y;n.TrackEvent=ha;n.Cancel=function(){this.C()};t.Tracker=V;t.Cancel=u(G,"cancel")}for(var qa,
ia={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:11,visitor:4},na=[],l=0;64>l;)na[l]=0|4294967296*D.abs(D.sin(++l));var Fa=function(a){var b,c,d,e,h=[];a=unescape(S(a));for(var f=a[F],k=[b=1732584193,c=-271733879,~b,~c],g=0;g<=f;)h[g>>2]|=(a.charCodeAt(g)||128)<<8*(g++%4);h[a=16*(f+8>>6)+14]=8*f;for(g=0;g<a;g+=16){f=k;for(e=0;64>e;)f=[d=f[3],H(b=f[1],(d=H(H(f[0],[b&(c=f[2])|~b&d,d&b|~d&c,b^c^d,c^(b|~d)][f=
e>>4]),H(na[e],h[[e,5*e+1,3*e+5,7*e][f]%16+g])))<<(f=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21][4*f+e++%4])|d>>>32-f),b,c];for(e=4;e;)k[--e]=H(k[e],f[e])}for(a="";32>e;)a+=(k[e>>3]>>4*(1^e++&7)&15).toString(16);return a},I,aa,ba,da=0,P={},Da=0,x=g[ea]("a"),J=function(a){a===r&&(a=location.href);x.href=a;a={ua:x.pathname[B](/^([^\/]|$)/,"/$1"),ta:x.hash[B](/^#$/,""),B:x.protocol[B](/^:$/,"")||location.protocol,t:x.hostname||location.hostname,w:x.href,N:x.search,A:x.port};a.w.match(":"+a.A)||(a.A=
"");return a};m._gs=G;for(G.v="5.0";l=ma.shift();)G.apply({},l);if(L){L=g[fa]("script");for(var l=L[F],oa;l--;)(oa=L[l].getAttribute("data-gs"))&&G(oa)}ka();C(m,"load",ka)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,1,0,"createElement","split","replace","length","toLowerCase","hasOwnProperty","getElementsByTagName","indexOf");
